---
- name: "Start Playboot"
  hosts: all 
  remote_user: root
  vars:
  - ansible_python_interpreter: "/usr/bin/python3"
  - docker_apt_ignore_key_error: true
  - docker_apt_gpg_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
  - docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
  - docker_apt_arch: "amd64"
  - docker_apt_release_channel: "stable"
  - http_proxy: "http://proxy:3128"
  - https_proxy: "http://proxy:3128"
  - no_proxy: ".example.local,127.0.0.1,127.0.1.1"
  - cgroupdriver: "SystemdCgroup = true"
  tasks: 
  - include_tasks:
      file: "tasks/main.yml"
